[project]
name = "computer-vision-basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.0",
    "open3d>=0.19.0",
    "opencv-contrib-python>=4.11.0.86",
    "pyproj>=3.7.2",
    "scipy>=1.16.3",
]
